# Configuration template for Gold Prediction Dataset Ingestion
# Copy this file to config.yaml and modify as needed

# Base data directory
data_dir: "data"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "data/processed/data_ingestion.log"

# Data sources configuration
sources:
  # USGS MRDS (Mineral Resource Data System)
  usgs:
    url: "https://mrdata.usgs.gov/mineral-resources/mrds-csv.zip"
    enabled: true
    # Filter commodities (case-insensitive, partial match)
    commodities_filter: ["Gold", "Au"]
    # Columns to keep from USGS dataset
    columns: [
      "site_name", "latitude", "longitude", "country", "state",
      "commodity", "orebody_type", "development_status"
    ]

  # SGC Geochemistry (Servicio Geológico Colombiano)
  sgc:
    # Path to SGC geochemical CSV file (download manually from SGC portal)
    csv_path: "data/raw/geoquimica_sgc.csv"
    enabled: true
    # Column mapping (adjust based on actual SGC file format)
    column_mapping:
      latitude: ["LATITUD"]
      longitude: ["LONGITUD"]
      gold_ppm: ["AU_PPM"]
      arsenic_ppm: ["AS_PPM"]
      copper_ppm: ["CU_PPM"]
      iron_ppm: ["FE_PPM"]
      antimony_ppm: ["SB_PPM"]
    # Gold threshold for labeling (ppm)
    gold_threshold: 0.1
    # CSV parsing options
    csv_options:
      separator: ";"  # Common separators: ",", ";", "|"
      encoding: "utf-8"  # Common encodings: "utf-8", "latin-1"

  # Borehole Data Integration (Caucasia Ground Truth - ITM-UdeA-UNAL 2025)
  borehole_data:
    # Colombian ground truth data (Caucasia, Antioquia - Cauca River basin)
    borehole_csv: "data/external/boreholes_caucasia.csv"
    lithology_column: "descripcion_litologia"  # Column containing lithology descriptions
    depth_column: "profundidad_m"  # Column containing depth information
    coordinates_columns: ["longitud", "latitud"]  # Coordinate columns
    gold_column: "au_ppm"  # Gold concentration column
    enabled: true
    # Colombian research methodology parameters
    research_methodology:
      borehole_count: 147  # Number of boreholes in Caucasia study
      sample_count: 8642  # Total samples from Colombian research
      study_area: "Caucasia_Antioquia_Cauca_River"  # Study area identifier
      validation_framework: true  # Use as ground truth for model validation
    # NLP processing for lithology text (following Colombian research)
    nlp_processing:
      use_glove_embeddings: true  # Use GloVe embeddings for lithology text
      embedding_dimension: 300  # GloVe embedding dimension
      max_sequence_length: 100  # Maximum text length for processing
      lithology_classes: 50  # Number of lithology classes for classification
      # Colombian research specific parameters
      text_preprocessing:
        remove_stopwords: true
        lemmatization: true
        technical_terms: true  # Keep geological technical terms

  # Hydrologic and Infrastructure Data (Colombian equivalents of OSM + USGS NHD)
  hydrology:
    # Colombian hydrologic data (IDEAM - Instituto de Hidrología, Meteorología y Estudios Ambientales)
    rivers_path: "data/external/hidrologia_colombia.gpkg"
    watersheds_path: "data/external/cuencas_colombia.gpkg"
    # Infrastructure data (from Colombian sources)
    infrastructure_path: "data/external/infraestructura_colombia.gpkg"
    enabled: true

  # Terrain Derivatives (following EarthScape methodology)
  terrain_derivatives:
    # DEM for derivative calculations
    dem_path: "data/external/aster_dem_colombia.tif"
    enabled: true
    # Calculated derivatives
    derivatives:
      slope: true
      aspect: true
      curvature: true
      hillshade: true
      elevation_percentile: true
      topographic_wetness_index: true
      flow_accumulation: true
    # Parameters for derivative calculations
    slope_units: "degrees"  # degrees or percent
    curvature_method: "standard"  # standard, plan, profile
    twi_exponent: 1.0  # Topographic Wetness Index exponent

  # Enhanced Multispectral Imagery (EarthScape RGB + NIR approach)
  multispectral:
    # Sentinel-2 bands (following EarthScape approach)
    sentinel2_bands: ["B02", "B03", "B04", "B08", "B11", "B12"]  # Blue, Green, Red, NIR, SWIR1, SWIR2
    # ASTER DEM for topographic correction
    aster_dem: "data/external/aster_dem_colombia.tif"
    enabled: true
    # Image preprocessing options
    preprocessing:
      atmospheric_correction: true
      topographic_correction: true
      cloud_masking: true
      band_stacking: true

  # Geological Map Data (Colombian Geological Survey)
  geological_map:
    # Path to geological map shapefile or geopackage
    map_path: "data/external/geological_map_colombia.gpkg"
    enabled: true
    # Lithology column name in the geological map
    lithology_column: "LITOLOGIA"
    # Age column name
    age_column: "EDAD"
    # Formation column name
    formation_column: "FORMACION"

  # Geophysical Data (Magnetic and Gravity Anomalies)
  geophysics:
    # Magnetic anomaly raster file
    magnetic_raster: "data/external/magnetic_anomalies_colombia.tif"
    # Gravity anomaly raster file
    gravity_raster: "data/external/gravity_anomalies_colombia.tif"
    enabled: true
    # Buffer distance for point sampling (meters)
    buffer_distance: 1000

  # Structural Geology Data (Faults and Structures)
  structural:
    # Path to faults and structures data
    faults_path: "data/external/faults_colombia.gpkg"
    structures_path: "data/external/structures_colombia.gpkg"
    enabled: true
    # Distance to nearest fault (meters)
    fault_proximity_distance: 5000
    # Structural complexity index calculation
    complexity_radius: 10000

  # ObservEarth Satellite Imagery API
  observearth:
    enabled: true  # Requires ObservEarth account and API credentials
    # API configuration (get from observearth.com)
    credentials:
      api_key: "${OBSERVEARTH_API_KEY}"        # Your ObservEarth API key from env
      geometry_id: "${OBSERVEARTH_GEOMETRY_ID}"    # Your ObservEarth geometry ID from env
    # Satellite image configuration
    satellite:
      # Sentinel-2 item identifier (scene ID)
      item_id: "S2C_MSIL2A_20250320T045721_R119_T44QMG_20250320T103315"
      # Image format for downloads
      image_format: "png"
    # Spectral indices to calculate
    indices:
      ndvi: true         # Normalized Difference Vegetation Index
      clay_index: true   # Clay minerals index
      iron_index: true   # Iron oxides index

# Output configuration
output:
  # Coordinate Reference System
  crs: "EPSG:4326"
  # Colombia bounding box (for spatial filtering)
  colombia_bounds:
    west: -79.0
    south: -4.3
    east: -66.8
    north: 12.5

  # Output formats
  formats:
    csv: true
    geojson: true
    parquet: false  # Requires pyarrow

  # File naming
  naming:
    master_dataset: "gold_dataset_master"
    timestamp_suffix: true

# Processing options
processing:
  # Batch size for API calls and processing
  batch_size: 100
  # Number of parallel workers (for CPU-intensive tasks)
  workers: 4
  # Timeout for API requests (seconds)
  request_timeout: 60
  # Retry attempts for failed requests
  max_retries: 3

# Data quality filters
quality_filters:
  # Remove points outside Colombia bounds
  spatial_filter: true
  # Remove duplicate coordinates
  remove_duplicates: true
  # Minimum elevation (meters)
  min_elevation: -100
  # Maximum elevation (meters)
  max_elevation: 6000
  # Remove points with missing critical data
  remove_incomplete: false

# Advanced options
advanced:
  # Cache downloaded data
  cache_enabled: true
  cache_dir: "data/cache"
  # Compress large files
  compression: true
  # Verbose output
  verbose: false

# Example SGC column formats (for reference)
# Uncomment and modify if your SGC file has different column names
# sgc_example_columns:
#   - "ID_MUESTRA"
#   - "LATITUD"
#   - "LONGITUD"
#   - "AU_PPM"
#   - "AS_PPM"
#   - "CU_PPM"
#   - "FE_PPM"
#   - "SB_PPM"
#   - "FECHA_MUESTREO"
#   - "PROYECTO"
