name: Keep Render Service Awake

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes (UTC)
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: keep-alive-render
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping health endpoint
        run: |
          set -euo pipefail
          URL="https://geoaupredict.onrender.com/health"
          echo "Pinging $URL"
          for i in 1 2 3; do
            if curl -fsS --max-time 10 "$URL" > /dev/null; then
              echo "Service responded (attempt $i)"; exit 0
            fi
            sleep 10
          done
          echo "Service did not respond after retries" >&2
          exit 1

